apiVersion: apps/v1
kind: Deployment
metadata: 
 name: webapp
 labels:
  type: proxy
  author: intelliqit
spec:
 replicas: 2
 selector:
  matchLabels:
   type: proxy
 template:
  metadata:
   name: webapp
   labels:
    type: proxy
  spec:
   containers:
    - name: nginx-container
      image: rajkumar02/webapp:v1
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
